from model.keypoint_classifier.keypoint_classifier import KeyPointClassifier
from model.point_history_classifier.point_history_classifier import PointHistoryClassifier
from model.point_history_classifier.point_history_classifier_allkeypoints import PointHistoryClassifier_allkeypoints